In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a * 2)

[2 4 6 8]


In [ ]:
#Find the product of the two matrices and store it into a file
#create a student dictionary roll no -> name mapping, demonstrate its operations on both sides: key -> value & vice verca
#crreate a matrix of 2d array and find row sum and column sum
#create a 3d matrix and row and columns sums
#create a matrix (2d) with random numbers then sort each row of that matrix

In [6]:
#1. Find the product of the two matrices and store it into a file
import numpy as np
M = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
N = np.array([
    [9,8,7],
    [6,5,4],
    [3,2,1]
])
print("Matrix M:")
print(M)
print()
print("Matrix N:")
print(N)
print()
P = np.dot(M, N)
print("Product of matrices M and N:")
print(P)

Matrix M:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix N:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Product of matrices M and N:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [1]:
import numpy as np

#create a student dictionary roll no -> name mapping, demonstrate its operations on both sides: key -> value & vice verca
student_dict = {57: "Alice", 58: "Bob", 59: "Charlie"}
print("Student Dictionary:")
print(student_dict)

#convert keys and values to numpy arrays
roll_nos = np.array(list(student_dict.keys()))
names = np.array(list(student_dict.values()))

#key -> value
roll_no = 58
index = np.where(roll_nos == roll_no)[0][0]
print(f"Name of student with roll number {roll_no}: {names[index]}")

#value -> key
name = "Charlie"
index = np.where(names == name)[0][0]
print(f"Roll number of student {name}: {roll_nos[index]}")

Student Dictionary:
{57: 'Alice', 58: 'Bob', 59: 'Charlie'}
Name of student with roll number 58: Bob
Roll number of student Charlie: 59


In [1]:
import numpy as np

#create a matrix of 2d array and find row sum and column sum
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

row_sums = matrix.sum(axis=1)
column_sums = matrix.sum(axis=0)

print("Matrix:")
print(matrix)

print("\nRow Sums:", row_sums)
print("Column Sums:", column_sums)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Row Sums: [ 6 15 24]
Column Sums: [12 15 18]


In [7]:
import numpy as np

#create a 3d matrix and row and columns sums
matrix_3d = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
])

print("3D Matrix:")
print(matrix_3d)
print()
#row sums (sum across columns, within each layer)
row_sums_3d = matrix_3d.sum(axis=2)
print("Row Sums (per layer):")
print(row_sums_3d)
print()

#column sums (sum down the rows, within each layer)
column_sums_3d = matrix_3d.sum(axis=1)
print("Column Sums (per layer):")
print(column_sums_3d)

3D Matrix:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

Row Sums (per layer):
[[ 6 15 24]
 [33 42 51]
 [60 69 78]]

Column Sums (per layer):
[[12 15 18]
 [39 42 45]
 [66 69 72]]


In [11]:
import numpy as np

#create a matrix (2d) with random numbers then sort each row of that matrix
matrix = np.random.randint(1, 101, size=(3, 3))

print("Original Matrix:")
print(matrix)
print()
#Sort each row
sorted_matrix = np.sort(matrix, axis=1)

print("Matrix with Sorted Rows:")
print(sorted_matrix)

Original Matrix:
[[ 9 59 21]
 [ 8 90 62]
 [65 60  9]]

Matrix with Sorted Rows:
[[ 9 21 59]
 [ 8 62 90]
 [ 9 60 65]]
